version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-ci
    privileged: true
    user: root
    ports: 
      - 8080:8080
    volumes: 
      - ./jenkins_home/:/var/jenkins_home
      - ./jenkins_var/var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_usr/usr/local/bin/docker:/usr/local/bin/docker
    restart: always